### ISSUE TITLE
Clean target should not delete readme.md

### ISSUE THREAD

**Issue by richfitz** [dfalster/Falster_2005_JEcol_data#5]
If readme.md is generated from readme.Rmd _but also stored under vc_, then perhaps a better clean recipe  would be:

```
clean:
    git checkout -- readme.md
```

which just gets the previously checked in version back out of git.

(Hope you don't mind - I think this is terrific and just want to help a bit.  I've got some other suggestions if you want them).

**Comment by dfalster** [comment]
Don't mind at all - I really appreciate suggestions and feedback.
